# Generated by Django 5.0.6 on 2024-06-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
