# Generated by Django 5.0.6 on 2024-06-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_category_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
